### ISSUE TITLE
从notion-hexo模板里新增文章提示报错

### ISSUE THREAD

**Issue by c55kai** [elog-x/notion-hexo#3]
## 同步模板里的文章就没问题
![image](https://github.com/elog-x/notion-hexo/assets/3049730/605dcf33-7f14-4a68-8d4b-4cc3c8f98848)

## 运行hexo后也正常显示
![image](https://github.com/elog-x/notion-hexo/assets/3049730/3659e4bd-9a45-44aa-b09c-5537040272f3)

## 但是自己随便新增一个文章，下载就报错这个
![image](https://github.com/elog-x/notion-hexo/assets/3049730/75c77397-a780-4bd1-8883-93b21b27d2de)
![image](https://github.com/elog-x/notion-hexo/assets/3049730/86f68b7d-b311-46f1-bf95-2772e3de0299)

**Comment by LetTTGACO** [comment]
才看到。。。 解决了吗？

**Comment by Aj002Th** [comment]
我今天刚开始使用 elog，使用该仓库时也遇到了完全一致的问题，想了解一下有什么解决办法吗？

**Comment by Aj002Th** [comment]
![bug](https://github.com/elog-x/notion-hexo/assets/70422354/6122fc94-d2f0-47b9-b844-52ed577c47b9)


> 我今天刚开始使用 elog，使用该仓库时也遇到了完全一致的问题，想了解一下有什么解决办法吗？

**Comment by Aj002Th** [comment]
![xiezuo20240419-154334](https://github.com/elog-x/notion-hexo/assets/70422354/7cffb429-5e53-4178-a8fb-480f82303044)
我的问题解决了，猜测原因是由于，在notion 里新增的文章没有设置cover，导致了图中获取的 url 是空值，引发报错。当新增的notion文章设置了 cover 就能正常运行了。

感觉这块的设计确实有一点疏忽，也许能为没有设置 cover 的博客跳过相关的图片 url 处理 or 在 readme 中说明哪些配置是必须的。

@LetTTGACO 最后还是感谢大哥能提供这种方便的工具：）

**Comment by LetTTGACO** [comment]
有点怪 不应该啊，我不会强制要求用户设置 cover 的，这个函数是扫描文章内的图片来上传的

**Comment by LetTTGACO** [comment]
知道问题了，这个模版会 使用自定义处理器来上传 notion 文章中的 cover图片，也就是在format-image.js中的处理

但是我忽略了用户可能并不会设置 cover 图片，这里忘记进行判空
![image](https://github.com/elog-x/notion-hexo/assets/37357188/a0be1f1a-1063-446b-8609-e86dfd2b4f7c)

你可以按照图片手动加上这个判空，就不会有问题了

**Comment by LetTTGACO** [comment]
我也已经更新模版仓库相关代码，感谢反馈
